# Generated by Django 4.2 on 2023-04-30 06:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, null=True, validators=[products.models.validate_rating]),
        ),
    ]
