# Generated by Django 4.2 on 2023-05-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
        ('products', '0006_rename_sub_category_product_subcategory'),
    ]

    operations = [
    ]
