<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-02 08:01
=======
# Generated by Django 4.2 on 2023-05-02 05:08
>>>>>>> 75421d2bd4a73571560359ba44ac38b7d0ffca07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('products', '0007_merge_20230502_1401'),
=======
        ('products', '0007_merge_20230502_1108'),
>>>>>>> 75421d2bd4a73571560359ba44ac38b7d0ffca07
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
