# Generated by Django 4.2 on 2023-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=10),
        ),
    ]
