# Generated by Django 4.2 on 2023-04-22 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
