# Generated by Django 4.2 on 2023-04-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'verbose_name': 'warehouse item', 'verbose_name_plural': 'warehouse items'},
        ),
    ]
