# Generated by Django 4.2 on 2023-04-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
        ("shop", "0002_remove_shop_user"),
    ]

    operations = []
