# Generated by Django 4.2 on 2023-04-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_merge_0002_initial_0002_remove_shop_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="seller",
        ),
    ]
