# Generated by Django 4.2 on 2023-05-02 17:43

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_warehouseitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rate_cnt',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=5, validators=[shop.models.validate_rating], verbose_name='Rating'),
        ),
    ]
