# Generated by Django 4.2 on 2023-04-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_seller_alter_shop_name_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
    ]
