# Generated by Django 4.2 on 2023-04-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_count_and_more'),
        ('shop', '0004_remove_warehouse_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='WarehouseItem',
        ),
    ]
