# Generated by Django 4.2 on 2023-04-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_rename_warehouse_warehouseitem'),
        ('orders', '0002_alter_order_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Order Details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='warehouse_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.warehouseitem'),
            preserve_default=False,
        ),
    ]
